[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pda_rent_payer = "8R1pBZKFyvBdR7LDa4R45JWSdUFnJdRSo9P1MPr571LC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
