[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
create_token = "FThBfjqE8JBZYX8SdiJtDZwwGuVaQVMFfcR9JEsxS2A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
