[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_minter = "D6HXvkuQVEF1Waki5P3RRtyBkC9Y7xsCVnmBVfi6kvBV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
