[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
spl_token_minter = "DmrXSUGWYaqtWg8sbi9JQN48yVZ1y2m7HvWXbND52Mcw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
