[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
create_account_program = "2QW7eymLrxC1TJmjTqtfnwvD8ND4dmVuHziX5p6sWzjj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
